name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  bloc: ^9.1.0
  build_runner: ^2.10.3
  connectivity_plus: ^7.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_markdown_plus: ^1.0.5
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.0
  home_widget: ^0.8.1
  http: ^1.6.0
  hydrated_bloc: ^10.1.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1
  logging: ^1.3.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  # workmanager: ^0.9.0+3
  workmanager: 0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
